repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    # Generic
    -   id: check-added-large-files # Prevent giant files from being committed
    -   id: check-case-conflict # Check for files with names that would conflict on a case-insensitive filesystem like MacOS HFS+ or Windows FAT
    -   id: check-merge-conflict # Check for files that contain merge conflict strings
    -   id: check-shebang-scripts-are-executable # Checks that scripts with shebangs are executable
    -   id: check-symlinks # Checks for symlinks which do not point to anything
    -   id: destroyed-symlinks # Detects symlinks which are changed to regular files with a content of a path which that symlink was pointing to
    -   id: detect-aws-credentials # Checks for the existence of AWS secrets that you have set up with the AWS CLI
    -   id: detect-private-key # Checks for the existence of private keys
    -   id: double-quote-string-fixer # This hook replaces double quoted strings with single quoted strings
    -   id: end-of-file-fixer # Makes sure files end in a newline and only a newline
    -   id: fix-byte-order-marker # removes UTF-8 byte order marker
    -   id: trailing-whitespace # Trims trailing whitespace
    # -   id: check-executables-have-shebangs # Checks that non-binary executables have a proper shebang
    # -   id: file-contents-sorter # Sort the lines in specified files (defaults to alphabetical). Requires list of target files as input
    # -   id: forbid-new-submodules # forbid-new-submodules
    # -   id: mixed-line-ending # Replaces or checks mixed line ending
    # -   id: no-commit-to-branch # Protect specific branches from direct checkins
    # YAML
    -   id: check-yaml # Attempts to load all yaml files to verify syntax
    # -   id: sort-simple-yaml # Sorts simple YAML files which consist only of top-level keys, preserving comments and blocks
    # JSON
    # -   id: pretty-format-json # Checks that all your JSON files are pretty
    # -   id: check-json # Attempts to load all json files to verify syntax
    # XML
    # -   id: check-xml # Attempts to load all xml files to verify syntax
    # TOML
    # -   id: check-toml # Attempts to load all TOML files to verify syntax
    # Python
    # -   id: check-docstring-first # Checks for a common error of placing code before the docstring
    # -   id: check-builtin-literals # Require literal syntax when initializing empty or zero Python builtin types
    # -   id: check-ast # Simply check whether files parse as valid python
    # -   id: debug-statements # Check for debugger imports and py37+ breakpoint() calls in python source
    # -   id: fix-encoding-pragma # Add # -*- coding: utf-8 -*- to the top of python files
    # -   id: name-tests-test # Assert that files in tests/ end in _test.py
    # -   id: requirements-txt-fixer # requirements-txt-fixer
